// Deterministic answers for "what does this mean?" questions. Written here
// (not generated by the model) so the safety wording is always exact, and no
// eBird call is ever needed to answer them.

const EXPLANATIONS = {
  pin_colors:
    "The colored map pins show report freshness — how old the most recent returned eBird report is at each location. " +
    "Green means a fresh report (0–7 days old), amber means a recent report (8–14 days old), and red means an older report (15+ days old). " +
    "The blue pin is the location you have selected. Pin colors only show how old the returned report is — they do not show how likely the bird is to be present.",

  category_labels:
    "Labels like “Frequently reported nearby” and “Occasionally reported nearby” describe how many nearby report locations came back in recent returned eBird data for the selected area and timeframe: " +
    "10 or more returned locations shows as frequently reported, 3–9 as occasionally reported, and 1–2 as rarely reported or few recent reports. " +
    "“Notable or uncommon nearby” means eBird flagged those reports as locally notable. " +
    "These categories are based on recent returned eBird data — they do not measure true abundance and do not guarantee the bird is currently present.",

  presence_guarantee:
    "No — BirdSights never guarantees a bird is present. It shows the most recent eBird report for a bird at each returned location within the selected timeframe. " +
    "A recent report means someone reported the bird there recently; the bird may or may not still be in the area. " +
    "BirdSights also does not show every checklist from each location, so results reflect recent returned reports only.",

  general:
    "BirdSights helps you discover birds using recent eBird reports. You can search for a specific bird near a location, ask a question in plain English, " +
    "or use Explore Birds Near You to see which birds have been recently reported near you. " +
    "Everything shown is based on recent returned eBird data — it does not measure true abundance and does not guarantee a bird is currently present.",
};

function getExplanation(topic) {
  return EXPLANATIONS[topic] || EXPLANATIONS.general;
}

module.exports = { getExplanation };
